sudo: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_script:
  # Use DEBUG mode to ensure more accurate tests.
  - export "DEBUG=1"
after_success:
  - set -e
  - if [ "$TRAVIS_NODE_VERSION" = "10" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./release.sh; fi
